### ISSUE TITLE
JCenter Shutting Down

### ISSUE THREAD

**Issue by Mustard** [amdelamar/jotp#26]
Hi,

Firstly thanks for the awesome library!

I'm not sure if you are aware but JCenter is shutting down https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter 

I can't imagine what this means for Android ecosystem etc who heavily use Jcenter

Anyways perhaps it's worth looking at publishing releases to another repository as well?

**Comment by amdelamar** [comment]
Yes, I need to get this and my other library, Jhash, published to Maven Central.

**Comment by amdelamar** [comment]
1. Replace `jcenter()` with `mavenCentral()`, and any dependencies if applicable.
2. Remove `bintray` gradle plugin.
3. Add `signing` plugin, and set other [gradle configs](https://docs.gradle.org/current/userguide/publishing_maven.html) needed. 
4. Create JIRA ticket with Sonatype OSSRH, get approved.
5. Publish lib to staging area.
6. Sync lib to Maven Central.
